from tracking_numbers import iter_courier_specs
from tracking_numbers import iter_definitions


def main():
    imports = [
        "import re",
        "",
        "from tracking_numbers.checksum_validator import Mod10",
        "from tracking_numbers.checksum_validator import Mod7",
        "from tracking_numbers.checksum_validator import NoChecksum",
        "from tracking_numbers.checksum_validator import S10",
        "from tracking_numbers.checksum_validator import SumProductWithWeightsAndModulo",
        "from tracking_numbers.definition import TrackingNumberDefinition",
        "from tracking_numbers.serial_number import DefaultSerialNumberParser",
        "from tracking_numbers.serial_number import PrependIf",
        "from tracking_numbers.serial_number import UPSSerialNumberParser",
        "from tracking_numbers.types import Courier",
        "from tracking_numbers.types import Product",
    ]

    with open("tracking_numbers/_generated.py", "w") as wf:
        wf.write("# DO NOT EDIT - Generated by codegen.py\n")
        wf.write("\n")
        for import_stmt in imports:
            wf.write(f"{import_stmt}\n")

        wf.write("\n\n")
        wf.write("DEFINITIONS = [\n")
        for courier_spec in iter_courier_specs():
            for definition, _ in iter_definitions(courier_spec):
                wf.write(f"  {repr(definition)},\n")

        wf.write("]\n")


if __name__ == "__main__":
    main()
